api_key: "PASTE YOUR API KEY HERE PLEASE!!!!"
base_url: "https://openrouter.ai/api/v1"
database_file: "chat_history.db"
default_model: "google/gemini-2.0-flash-lite-preview-02-05:free"
history_file: ".chat_history"
